import { Bell, CalendarDays, ChevronRight, CircleCheck, Clock3, Flame, LogOut, Plus, Sparkles, Target, TrendingUp } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import AddTaskModal from './components/AddTaskModal'
import AuthScreen from './components/AuthScreen'
import ProgressBar from './components/ProgressBar'
import Sidebar from './components/Sidebar'
import TaskCard from './components/TaskCard'
import { getRegisteredUsers, getSession, logoutUser } from './utils/auth'
import { loadPreferences, loadTasks, savePreferences, saveTasks, seedTasks } from './utils/storage'
import { formatDate, formatTime, getNextTask, getStats, taskStatus, todayKey } from './utils/taskUtils'

const pageMeta = { dashboard: ['Good evening', 'Here is your focus for today.'], routine: ['Daily routine', 'Build momentum with intentional blocks.'], planner: ['30-day planner', 'A clear path is made one day at a time.'], progress: ['Progress analytics', 'Small wins compound into remarkable results.'], notifications: ['Notifications', 'Stay in the loop without losing your flow.'], settings: ['Settings', 'Shape PLAN_ZEN around the way you work.'] }

function App() {
  const [session, setSession] = useState(getSession)
  if (!session) return <AuthScreen onAuthenticated={setSession} />
  return <Workspace session={session} onLogout={() => { logoutUser(); setSession(null) }} />
}

function Workspace({ session, onLogout }) {
  const [tasks, setTasks] = useState(() => loadTasks(session.id))
  const [preferences, setPreferences] = useState(() => ({ ...loadPreferences(session.id), name: session.name }))
  const [page, setPage] = useState('dashboard')
  const [menuOpen, setMenuOpen] = useState(false)
  const [modal, setModal] = useState(null)
  const [plannerDay, setPlannerDay] = useState(1)
  const [toast, setToast] = useState('')
  const today = todayKey()
  const stats = useMemo(() => getStats(tasks), [tasks])
  const nextTask = useMemo(() => getNextTask(tasks), [tasks])
  const activeTasks = useMemo(() => tasks.filter((task) => task.date === today).sort((a, b) => a.startTime.localeCompare(b.startTime)), [tasks, today])

  useEffect(() => saveTasks(tasks, session.id), [tasks, session.id])
  useEffect(() => savePreferences(preferences, session.id), [preferences, session.id])
  useEffect(() => {
    const timer = window.setInterval(() => {
      tasks.filter((task) => !task.completed && task.date === today && task.startTime === new Date().toTimeString().slice(0, 5)).forEach((task) => notify(task))
    }, 30000)
    return () => window.clearInterval(timer)
  }, [tasks, today])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer) }, [toast])

  function notify(task) { if ('Notification' in window && Notification.permission === 'granted') new Notification('PLAN_ZEN', { body: `Time to focus: ${task.subject} — ${task.title}` }); setToast(`Reminder: ${task.title}`) }
  async function enableNotifications() { if (!('Notification' in window)) { setToast('Browser notifications are not supported here.'); return } const permission = await Notification.requestPermission(); setPreferences((current) => ({ ...current, notifications: permission === 'granted' })); setToast(permission === 'granted' ? 'Notifications are now active.' : 'Notification permission was not granted.') }
  function saveTask(task) { setTasks((current) => current.some((item) => item.id === task.id) ? current.map((item) => item.id === task.id ? task : item) : [...current, task]); setModal(null); setToast('Plan updated') }
  function toggleTask(id) { setTasks((current) => current.map((task) => task.id === id ? { ...task, completed: !task.completed } : task)) }
  function deleteTask(id) { setTasks((current) => current.filter((task) => task.id !== id)); setToast('Task removed') }
  function resetPlan() {
    const freshPlan = seedTasks.map((task) => ({ ...task, id: crypto.randomUUID(), completed: false }))
    setTasks(freshPlan)
    setToast('Plan reset to default')
  }
  function navigate(next) { if (next === '__menu') { setMenuOpen(true); return } setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <div className="app-shell"><Sidebar activePage={page} onNavigate={navigate} open={menuOpen} onClose={() => setMenuOpen(false)} /><main className="main-content"><header className="topbar"><div><span className="section-kicker">{page === 'dashboard' ? new Date().toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) : 'PLAN_ZEN workspace'}</span><h1>{page === 'dashboard' ? `${pageMeta[page][0]}, ${session.name.split(' ')[0]}` : pageMeta[page][0]}</h1><p>{pageMeta[page][1]}</p></div><div className="topbar-actions"><button className="notification-button" onClick={() => navigate('notifications')} aria-label="Open notifications"><Bell size={18} /><span /></button><div className="profile-chip"><div className="avatar">{session.name.charAt(0).toUpperCase()}</div><span>{session.name}</span><button className="icon-button" onClick={onLogout} aria-label="Sign out"><LogOut size={14} /></button></div></div></header>
    {page === 'dashboard' && <Dashboard stats={stats} tasks={activeTasks} nextTask={nextTask} onAdd={() => setModal({})} onNavigate={navigate} onToggle={toggleTask} onEdit={(task) => setModal(task)} onDelete={deleteTask} />}
    {page === 'routine' && <Routine tasks={activeTasks} onAdd={() => setModal({ defaultDate: today })} onToggle={toggleTask} onEdit={(task) => setModal(task)} onDelete={deleteTask} />}
    {page === 'planner' && <Planner tasks={tasks} day={plannerDay} setDay={setPlannerDay} onAdd={() => setModal({ defaultPlanDay: plannerDay })} onToggle={toggleTask} onEdit={(task) => setModal(task)} onDelete={deleteTask} />}
    {page === 'progress' && <Progress tasks={tasks} />}
    {page === 'notifications' && <Notifications tasks={tasks} enabled={preferences.notifications} onEnable={enableNotifications} />}
    {page === 'settings' && <Settings preferences={preferences} setPreferences={setPreferences} onEnable={enableNotifications} isOwner={session.isOwner} onResetPlan={resetPlan} />}
  </main>{modal && <AddTaskModal task={modal.id ? modal : null} defaultDate={modal.defaultDate} defaultPlanDay={modal.defaultPlanDay} onSave={saveTask} onClose={() => setModal(null)} />}{toast && <div className="toast"><CircleCheck size={17} />{toast}</div>}</div>
}

function Dashboard({ stats, tasks, nextTask, onAdd, onNavigate, onToggle, onEdit, onDelete }) { return <div className="page-content"><section className="hero-grid"><div className="hero-card"><div className="hero-glow" /><div className="eyebrow"><Sparkles size={14} /> YOUR DAILY PULSE</div><div className="hero-percent">{stats.progress}<span>%</span></div><p>of today's plan is complete</p><ProgressBar value={stats.progress} accent /><div className="hero-footer"><span><Flame size={15} /> {stats.completed} day streak</span><span>Keep going, you're close</span></div></div><div className="next-card"><div className="card-heading"><span className="eyebrow">NEXT UP</span><Clock3 size={17} /></div>{nextTask ? <><div className="next-time">{formatTime(nextTask.startTime)}</div><h2>{nextTask.title}</h2><p>{nextTask.subject} <span className="dot-separator">•</span> {nextTask.description}</p><button className="text-button" onClick={() => onEdit(nextTask)}>View task <ChevronRight size={15} /></button></> : <><h2>Clear horizon</h2><p>You've completed everything on your schedule. Enjoy the space.</p></>}</div></section><section className="section-row"><div><span className="eyebrow">TODAY'S OVERVIEW</span><h2>Make it count.</h2></div><button className="button button-primary" onClick={onAdd}><Plus size={17} /> Add task</button></section><section className="stat-grid"><Stat label="Total tasks" value={stats.total} icon={Target} color="cyan" /><Stat label="Completed" value={stats.completed} icon={CircleCheck} color="green" /><Stat label="In progress" value={stats.pending} icon={TrendingUp} color="yellow" /><Stat label="Missed" value={stats.missed} icon={Clock3} color="red" /></section><section className="content-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">FOCUS QUEUE</span><h2>Today's routine</h2></div><button className="text-button" onClick={() => onNavigate('routine')}>View all <ChevronRight size={15} /></button></div><div className="task-list">{tasks.length ? tasks.slice(0, 4).map((task) => <TaskCard key={task.id} task={task} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} />) : <EmptyState onAdd={onAdd} />}</div></div><div className="panel insight-panel"><div className="panel-heading"><div><span className="eyebrow">MOMENTUM</span><h2>Weekly rhythm</h2></div><TrendingUp size={18} className="accent-icon" /></div><div className="mini-chart">{[62, 38, 84, 55, 72, 48, stats.progress].map((height, index) => <div className="chart-column" key={index}><div style={{ height: `${Math.max(height, 8)}%` }} className={index === 6 ? 'today-column' : ''} /><small>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][index]}</small></div>)}</div><div className="chart-note"><strong>{stats.progress}%</strong><span>today's completion</span></div></div></section></div> }
function Stat({ label, value, icon: Icon, color }) { return <div className="stat-card"><div className={`stat-icon ${color}`}><Icon size={17} /></div><div><span>{label}</span><strong>{value}</strong></div></div> }
function EmptyState({ onAdd }) { return <div className="empty-state"><CalendarDays size={25} /><p>Your routine is clear.</p><button className="text-button" onClick={onAdd}>Add your first task <Plus size={14} /></button></div> }
function Routine({ tasks, onAdd, onToggle, onEdit, onDelete }) { return <div className="page-content"><section className="section-row intro-row"><div><span className="eyebrow">{formatDate(todayKey()).toUpperCase()}</span><h2>A routine that respects your energy.</h2></div><button className="button button-primary" onClick={onAdd}><Plus size={17} /> Add task</button></section><div className="routine-toolbar"><span>{tasks.length} scheduled blocks</span><span className="status-key"><i className="key-dot green" /> Complete <i className="key-dot yellow" /> Pending <i className="key-dot red" /> Missed</span></div><div className="task-list routine-list">{tasks.length ? tasks.map((task) => <TaskCard key={task.id} task={task} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} />) : <EmptyState onAdd={onAdd} />}</div></div> }
function Planner({ tasks, day, setDay, onAdd, onToggle, onEdit, onDelete }) { const dayTasks = tasks.filter((task) => Number(task.planDay) === day); return <div className="page-content"><section className="planner-header"><div><span className="eyebrow">THE LONG GAME</span><h2>Thirty days. One direction.</h2><p>Design the season you want to live in.</p></div><button className="button button-primary" onClick={onAdd}><Plus size={17} /> Add to day {day}</button></section><div className="day-grid">{Array.from({ length: 30 }, (_, index) => { const current = index + 1; const dayItems = tasks.filter((task) => Number(task.planDay) === current); const done = dayItems.filter((task) => task.completed).length; return <button key={current} onClick={() => setDay(current)} className={`day-tile ${current === day ? 'selected' : ''}`}><span>DAY</span><strong>{String(current).padStart(2, '0')}</strong><small>{dayItems.length ? `${done}/${dayItems.length} done` : 'Open slate'}</small>{dayItems.length > 0 && <ProgressBar value={(done / dayItems.length) * 100} />}</button> })}</div><section className="panel planner-day-panel"><div className="panel-heading"><div><span className="eyebrow">DAY {String(day).padStart(2, '0')}</span><h2>{dayTasks.length ? `${dayTasks.length} focus blocks` : 'Your next chapter starts here'}</h2></div><span className="day-date">{dayTasks.length ? formatDate(dayTasks[0].date) : 'Ready when you are'}</span></div><div className="task-list">{dayTasks.length ? dayTasks.map((task) => <TaskCard key={task.id} task={task} onToggle={onToggle} onEdit={onEdit} onDelete={onDelete} />) : <EmptyState onAdd={onAdd} />}</div></section></div> }
function Progress({ tasks }) { const allCompleted = tasks.filter((task) => task.completed).length; const overall = tasks.length ? Math.round((allCompleted / tasks.length) * 100) : 0; const days = Array.from({ length: 7 }, (_, index) => { const d = new Date(); d.setDate(d.getDate() - (6 - index)); const key = d.toISOString().slice(0, 10); return { label: d.toLocaleDateString([], { weekday: 'short' }).slice(0, 2), ...getStats(tasks, key) } }); return <div className="page-content"><section className="analytics-hero"><div><span className="eyebrow">ALL SYSTEMS</span><h2>Your consistency is your superpower.</h2><p>Keep showing up. The results are already in motion.</p></div><div className="big-progress"><strong>{overall}<small>%</small></strong><ProgressBar value={overall} accent /><span>30-day completion</span></div></section><section className="stat-grid analytics-stats"><Stat label="Completed" value={allCompleted} icon={CircleCheck} color="green" /><Stat label="Pending" value={tasks.filter((task) => taskStatus(task) === 'pending').length} icon={TrendingUp} color="yellow" /><Stat label="Missed" value={tasks.filter((task) => taskStatus(task) === 'missed').length} icon={Clock3} color="red" /><Stat label="Total planned" value={tasks.length} icon={Target} color="cyan" /></section><section className="panel analytics-panel"><div className="panel-heading"><div><span className="eyebrow">LAST 7 DAYS</span><h2>Weekly progress</h2></div><span className="trend-label"><TrendingUp size={14} /> +12.4%</span></div><div className="week-chart">{days.map((day) => <div className="week-column" key={day.label}><div className="week-bar"><span style={{ height: `${day.progress}%` }} /></div><strong>{day.progress}%</strong><small>{day.label}</small></div>)}</div></section></div> }
function Notifications({ tasks, enabled, onEnable }) { return <div className="page-content"><section className="notification-hero"><div className="notification-orb"><Bell size={27} /></div><div><span className="eyebrow">SMART REMINDERS</span><h2>Be where your attention is needed.</h2><p>PLAN_ZEN checks your schedule and nudges you at the right moment.</p></div><button className={`button ${enabled ? 'button-success' : 'button-primary'}`} onClick={onEnable}>{enabled ? 'Notifications active' : 'Enable notifications'}</button></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">UPCOMING</span><h2>Scheduled reminders</h2></div></div><div className="notification-list">{tasks.filter((task) => !task.completed).slice(0, 6).map((task) => <div className="notification-row" key={task.id}><div className="notification-icon"><Bell size={16} /></div><div><strong>{task.title}</strong><p>{task.subject} · {formatDate(task.date)} at {formatTime(task.startTime)}</p></div><span className={`priority priority-${task.priority.toLowerCase()}`}>{task.priority}</span></div>)}</div></section></div> }
function Settings({ preferences, setPreferences, onEnable, isOwner, onResetPlan }) { const registeredUsers = isOwner ? getRegisteredUsers() : []; return <div className="page-content"><section className="settings-grid"><div className="panel settings-panel"><span className="eyebrow">PROFILE</span><h2>Your workspace</h2><label>Display name<input value={preferences.name} onChange={(event) => setPreferences({ ...preferences, name: event.target.value })} /></label><p className="setting-copy">This name appears in your daily greeting.</p></div><div className="panel settings-panel"><span className="eyebrow">REMINDERS</span><h2>Protect your focus</h2><div className="setting-toggle"><div><strong>Browser notifications</strong><p>Get a nudge when a task begins.</p></div><button className={`toggle ${preferences.notifications ? 'on' : ''}`} onClick={onEnable} aria-label="Toggle notifications"><span /></button></div><div className="setting-line"><span>Local-first storage</span><strong>Active</strong></div><div className="setting-line"><span>AI planning layer</span><strong className="muted">Coming next</strong></div><div className="setting-line reset-plan-line"><span>Reset plan</span><button className="button button-danger" onClick={onResetPlan}>Reset</button></div></div></section>{isOwner && <section className="panel registration-panel"><div className="panel-heading"><div><span className="eyebrow">OWNER CONSOLE</span><h2>Registration history</h2></div><span className="day-date">{registeredUsers.length} account{registeredUsers.length === 1 ? '' : 's'}</span></div><p className="setting-copy">New accounts registered on this device appear here.</p><div className="registration-list">{registeredUsers.map((user) => <div className="registration-row" key={user.id}><div className="avatar small-avatar">{user.name.charAt(0).toUpperCase()}</div><div><strong>{user.name}</strong><p>{user.email}</p></div><time>{new Date(user.registeredAt).toLocaleDateString([], { day: 'numeric', month: 'short', year: 'numeric' })}</time></div>)}</div></section>}</div> }

export default App
